project:
  type: website
  output-dir: _site
  resources:
    - google71bbe46973ffb153.html

website:
  title: "Home"
  site-url: "https://iarayad.github.io/"
  navbar:
    left:
      - contents/research.qmd
    right:
      - contents/letschat.qmd
  page-navigation: true

format:
  html:
    theme:
      - minty
    page-layout: full
    css: styles.css
    # toc: true
    backgroundcolor: "#f8f9fa"

execute:
  freeze: auto


