project:
  type: website
  output-dir: _site
  resources:
    - google71bbe46973ffb153.html
    - publickey.asc

website:
  title: "About me"
  site-url: "https://iarayad.github.io/"
  navbar:
    left:
      - contents/research.qmd
    right:
      - contents/letschat.qmd
    search: true
  page-navigation: true
  page-footer:
    center:
      - text: "ðŸ“§ isidora (at) araya.day"
      - text: "Get my GPG key"
        href: publickey.asc

format:
  html:
    theme:
      - minty
    page-layout: full
    css: styles.css
    scroll-reveal: true
    # toc: true
    backgroundcolor: "#f8f9fa"

execute:
  freeze: auto
