project:
  type: website
  output-dir: _site

website:
  title: "Home"
  site-url: "https://iarayad.github.io/"
  navbar:
    left:
      - contents/about.qmd
  page-navigation: true

format:
  html:
    theme:
      - minty
    page-layout: full
    css: styles.css
    toc: true
    backgroundcolor: "#f8f9fa"

execute:
  freeze: auto


