project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - about.qmd

format:
  html:
    theme:
      - minty
    page-layout: full
    css: styles.css
    toc: true
    backgroundcolor: "#f8f9fa"

execute:
  freeze: auto


