[workspace]
authors = ["Isidora Araya <iarayaday@gmail.com>"]
channels = ["conda-forge"]
name = "iarayad.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.1,<3"
scipy = ">=1.16.0,<2"
matplotlib = ">=3.10.3,<4"
plotly = ">=6.2.0,<7"
nbformat = ">=5.10.4,<6"
nbclient = ">=0.10.2,<0.11"
ipykernel = ">=6.29.5,<7"

pyyaml = ">=6.0.2,<7"
jupyter = ">=1.1.1,<2"
